### ISSUE TITLE
Uncaught TypeError: Cannot read property 'constructor' of undefined

### ISSUE THREAD

**Issue by plusallofyou** [Vertagon-Softworks/Chromo#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Mac OS X 10.14.6
**Thrown From**: [Chromo-Color-Previews](https://github.com/Vertagon-Softworks/Chromo) package 1.6.6

### Stack Trace

Uncaught TypeError: Cannot read property 'constructor' of undefined

```
At /Users/answerrocketguest/.atom/packages/Chromo-Color-Previews/lib/color-preview.js:54

TypeError: Cannot read property 'constructor' of undefined
    at /packages/Chromo-Color-Previews/lib/color-preview.js:54:17
    at Function.simpleDispatch (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at Workspace.didChangeActivePaneItemOnPaneContainer (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:423731)
    at WorkspaceCenter.paneContainer.onDidChangeActivePaneItem.t (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:43577)
    at Function.simpleDispatch (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at PaneContainer.didChangeActiveItemOnPane (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:446035)
    at PaneContainer.didActivatePane (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:445512)
    at Pane.activate (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:462930)
    at Pane.focus (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:454373)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
    at HTMLElement.attachedCallback (/app.asar/src/pane-element.js:16:12)
    at HTMLElement.PaneAxisElement.childAdded (/app.asar/src/pane-axis-element.js:92:12)
    at HTMLElement.PaneAxisElement.attachedCallback (/app.asar/src/pane-axis-element.js:26:27)
    at HTMLElement.rootChanged (/app.asar/src/pane-container-element.js:28:12)
    at Function.simpleDispatch (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1207528)
    at Emitter.emit (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:1208969)
    at PaneContainer.setRoot (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:443606)
    at PaneContainer.deserialize (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:442066)
    at WorkspaceCenter.deserialize (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:14:43804)
    at Workspace.deserialize (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:11:422299)
    at AtomEnvironment.deserialize (/Users/answerrocketguest/Downloads/Atom.app/Contents/Resources/app/static/<embedded>:1:715474)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.17 
atom-cobol 0.3.0 
atom-isort 2.6.3 
atom-material-ui 2.1.3 
atom-react-native-style 0.2.0 
atom-typescript 13.3.0 
autoclose-html 0.23.0 
autocomplete-python 1.14.1 
autocomplete-python-jedi 1.10.3-0 
better-git-blame 0.4.7 
bottom-dock 0.4.4 
browser-plus 0.0.98 
busy-signal 2.0.1 
Chromo-Color-Previews 1.6.6 
color-picker 2.3.0 
color-tabs 0.1.8 
css-color-name 0.4.0 
file-icons 2.1.33 
goto-definition 1.3.4 
Hydrogen 2.10.3 
hyperclick 0.1.5 
ide-json 0.2.1 
ide-python 1.4.2 
ide-typescript 0.9.1 
image-preview 0.4.0 
intentions 1.1.5 
kite 0.168.0 
language-graphql 1.0.0 
language-markdown 0.37.0 
language-nginx 0.8.0 
language-r 0.4.2 
language-sas 0.2.4 
linter 2.3.0 
linter-pycodestyle 2.1.3 
linter-ui-default 1.7.1 
MagicPython 1.1.1 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
minimap-linter 2.2.1 
nbviewer 1.0.2 
platformio-ide-terminal 2.9.3 
prettier-atom 0.57.2 
python-indent 1.2.3 
python-tools 0.6.9 
python-yapf 0.14.0 
pythonic-atom 0.2.9 
react 0.18.0 
script 3.18.1 
sort-lines 0.19.0 
svg-preview 0.14.0 
teletype 0.13.4 
todo-manager 0.2.10 
```

**Comment by matthaidet** [comment]
Fixed in latest patch
